import type { Metadata } from "next";
import "./globals.css";
// import Navbar from "./ui/components/navbar/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {/* <Navbar />  */}
        <main className="relative">
          {children}
        </main>
      </body>
    </html>
  );
}
